#!/bin/sh

#
# Acora IRC Services
# acora: Services remote control file
#
# Copyright (c) 2009 Acora (http://cia.vc/stats/project/acorairc)
# Written by Ricki, Henry, Shaun and help from others: irc.ircnode.org #acora
#
# This project is licensed under the GNU Public License
#
# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#

run=`ps ux | awk '/php (.*?)services.php/ && !/awk/ {print $2}'`
version="0.6.0beta"

if [ "$1" = "" ]
then
    	echo "Invalid use (start|stop|restart|debug|status|version)"
	exit
fi

if [ "$1" = "start" ]
then
    	if [ "$run" ]
    		then
        	echo "Acora IRC Services are already running."
		exit
    	else
		echo "Starting Acora IRC Services... Version: $version."
       		php -q extra/start.php
		exit
	fi
elif [ "$1" = "stop" ]
then
    	if [ "$run" ]
    	then
        	kill -9 $run
        	echo "Acora IRC Services shutting down."
       		exit
		else
        	echo "Acora IRC Services are not running."
        	exit
		fi
elif [ "$1" = "restart" ]
then
    	if [ "$run" ]
    	then
       		kill -9 $run
        	php -q extra/start.php
			exit
    	else
    		echo "Acora IRC Services are not running."
		exit
    	fi
elif [ "$1" = "debug" ]
then
    	if [ "$run" ]
    	then
        	echo "Acora IRC Services are already running."
			exit
    	else
		echo "Starting Acora IRC Services... Version: $version."
		echo "Running in debug mode."
       		php services.php debug	
		exit
	fi
elif [ "$1" = "status" ]
then
	if [ "$run" ]
    	then
        	echo "Acora IRC Services are running."
			exit
    	else
        	echo "Acora IRC Services are not running."
		exit
    	fi
elif [ "$1" = "version" ]
then
    	echo "Acora IRC Services version $version\033[m"
	exit
else
    	echo "Invalid use (start|stop|restart|debug|status|version)"
	exit
fi
